### PR TITLE
Add icon for mobile homescreens

### PR DESCRIPTION
**Pull request by AlfHou**
Related to #31.
Made a quick and dirty icon for home screens on mobile devices.
Also, don't be fooled by the `apple-touch-icon`, it works for Android as well (see discussion [here](https://stackoverflow.com/a/43469640)).

Here is the icon for reference:
touch-icon

### CODE REVIEW

**Comment by djjudas21** [comment]
Cool, I think it's really important to have an icon. Not sure how well the whole word Hammond would fit in a small icon though. Maybe better to have just the letter H or even an icon of a petrol/gas pump ⛽️ etc?

**Comment by AlfHou** [comment]
@djjudas21 I agree, it's better to not have text in the icon.
I found a Creative Commons licensed icon of a gas pump that I used. 
The icon now looks like this:
hammond_icon

**Comment by djjudas21** [comment]
I just noticed there's already an icon in use for the favicon, but I can't find it in the repo anywhere. I guess we should have the same icon for the `favicon` and the `apple-touch-icon`. If you've found a CC licensed one that's probably sensible as it can be scaled to whatever size we need.

Screenshot from 2022-03-07 11-32-45

P.S. I'm not a developer, just a sysadmin who happens to use Hammond :smile: I probably can't help with the code much

**Comment by AlfHou** [comment]
Yep, the favicon can be found in `ui/public`. However it's not usable for the app icon as it is simply a 16x16px icon, which wouldn't look great scaled up. The icon I found could be scaled down instead though.

Simply participating in the discussions here is of great help either way. Two heads are better than one and all that 😄

**Comment by djjudas21** [comment]
Great. You might as well overwrite the existing favicon with a scaled-down version of the new icon then, and wait for @akhilrex's approval

**Pull request merged**
